rust:
  - changed-files:
      - any-glob-to-any-file: ['**/*.rs', 'Cargo.toml', 'Cargo.lock']

cli:
  - changed-files:
      - any-glob-to-any-file: ['crates/crumb-cli/**', 'crates/crumb-repl/**']

platform:
  - changed-files:
      - any-glob-to-any-file: ['crates/crumb-platform/**']

website:
  - changed-files:
      - any-glob-to-any-file: ['crumb.elixpo/**']

marketplace:
  - changed-files:
      - any-glob-to-any-file: ['marketplace/**']

documentation:
  - changed-files:
      - any-glob-to-any-file: ['**/*.md', 'docs/**']

ci:
  - changed-files:
      - any-glob-to-any-file: ['.github/**']
