[package]
name = "crumb-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "crumb"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
crumb-core = { path = "../crumb-core" }
crumb-history = { path = "../crumb-history" }
crumb-native = { path = "../crumb-native" }
crumb-platform = { path = "../crumb-platform" }
crumb-pty = { path = "../crumb-pty" }
crumb-repl = { path = "../crumb-repl" }
crumb-ui = { path = "../crumb-ui" }
crossterm.workspace = true

[lints]
workspace = true
